import speech_recognition as sr
import cohere

recognizer = sr.Recognizer()

# Pre-recorded audio (.wav) file
with sr.AudioFile("harvard.wav") as source:
    audio = recognizer.record(source)
    text = recognizer.recognize_google(audio)  # Free Google API for testing
    print("Transcription:", text)
    
    print('-----')

# Accessing system mic for audio
with sr.Microphone() as source:
    print("Listening...")
    audio = recognizer.listen(source, timeout=20)
    text = recognizer.recognize_google(audio)
    print("Transcription:", text)

# Inculcated Cohere to summarise text generated by the Google API
co = cohere.Client("tjULV7khw6lZoXYJpNCrzlbAdDOZURYPx8EzYbgL")
response = co.generate(
    prompt=f"Summarize this: {text}",
    max_tokens=50,
    temperature=0.7
)
summary = response.generations[0].text.strip()
print("Summary:", summary)